module.exports.authService = require('./auth.service');
module.exports.emailService = require('./email.service');
module.exports.tokenService = require('./token.service');
module.exports.userService = require('./user.service');
module.exports.BrandService = require('./brand.service');
module.exports.ProductTypeService = require('./producttype.service');
// module.exports.productService = require('./product.service');
// module.exports.productvariantService = require('./product-variant.service');
// module.exports.productimageService = require('./product-image.service');
